import json
import os
import sys
import time

try:
    from nostr.relay_manager import RelayManager
    from nostr.event import Event
    from nostr.key import PrivateKey
except ImportError:
    print("Nostr library not found. Please run: pip install nostr")
    sys.exit(1)

# ==========================================
# VECTOR 6: THE CRYPTOGRAPHIC INJECTOR (NOSTR)
# ==========================================
# This script represents true "Zero-Center" autonomous publishing.
# It reads the narratives generated by Llama3 (Vector 6), spins up
# a cryptographic burner identity (or a dedicated proxy node key),
# connects to global decentralized relays, drops the payload, and vanishes.
# ==========================================

ACTIVE_ROOT = os.environ.get('ACTIVE_ROOT', os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TARGET_DIR = os.path.join(ACTIVE_ROOT, 'vault', 'amplification', 'contextualized')

# Essential public relays for high visibility
RELAYS = [
    "wss://relay.damus.io",
    "wss://nos.lol",
    "wss://relay.nostr.band",
    "wss://nostr.wine"
]

def load_burner_key():
    """Loads an existing private key from env, or generates a temporary burner key."""
    # Ensure you set NOSTR_NSEC in your environment to maintain a persistent proxy identity.
    # Otherwise, this generates a complete ghost (burner) that cannot be banned but doesn't build followers.
    nsec = os.environ.get('NOSTR_NSEC')
    if nsec:
        try:
            return PrivateKey.from_nsec(nsec)
        except Exception as e:
            print(f"Error loading provided NOSTR_NSEC: {e}. Generating burner...")
            
    # Pure burner node. Exists only for this payload injection.
    print("No NOSTR_NSEC provided. Initiating temporary burner protocol.")
    return PrivateKey()

def inject_payloads():
    print("🌀 Initiating Cryptographic Injector (Decentralized Nostr Spread)...")
    
    if not os.path.exists(TARGET_DIR):
        print(f"Directory {TARGET_DIR} not found. Run Llama3 contextualizer first.")
        return

    payloads = [f for f in os.listdir(TARGET_DIR) if f.endswith('.md')]
    
    if not payloads:
        print("No Vector 6 payloads found to inject.")
        return

    print(f"Loaded {len(payloads)} raw text payloads.")
    
    node_key = load_burner_key()
    print(f"Node Public Key (npub): {node_key.public_key.bech32()}")

    # Initialize decentralized relay connections
    relay_manager = RelayManager()
    for r in RELAYS:
        relay_manager.add_relay(r)
        
    print("Connecting to global Nostr relays...")
    relay_manager.open_connections({"cert_reqs": 0})
    time.sleep(2) # Allow websocket handshake

    for file in payloads:
        filepath = os.path.join(TARGET_DIR, file)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract just one of the narratives (e.g., The Urgent Alert) to avoid spamming the whole file
        # We look for standard markdown boundaries from the Llama3 output
        parts = content.split("---")
        if len(parts) > 1:
             # Grab the first actual content block after the title
             inject_text = parts[1].strip() 
        else:
             inject_text = content[:250] + "..." # Fallback substring

        if not inject_text:
            continue
            
        # Add tracking hashtag for the network effect
        inject_text += "\n\n#MutualAid #Solidarity"
        
        print(f"Injecting event payload from {file}...")
        
        event = Event(content=inject_text, public_key=node_key.public_key.hex())
        node_key.sign_event(event)

        relay_manager.publish_event(event)
        print("✅ Payload fired across relays.")
        
        # Avoid algorithmic throttling on relays
        time.sleep(3)

    print("Closing relay connections.")
    relay_manager.close_connections()
    print("Injections complete. Node vanishing.")

if __name__ == "__main__":
    inject_payloads()
